{"name": "test_logout", "status": "broken", "statusDetails": {"message": "NameError: name 'y' is not defined", "trace": "self = <login_test.TestLogin object at 0x03C9BF40>\n\n    def test_logout(self):\n>       y\nE       NameError: name 'y' is not defined\n\ntests\\login_test.py:27: NameError"}, "attachments": [{"name": "stdout", "source": "c959b42a-755e-45a6-80d5-b63310558568-attachment.txt", "type": "text/plain"}], "start": 1593934322891, "stop": 1593934322892, "uuid": "d7073ed1-9d6e-448c-aba1-aa18cd6133c3", "historyId": "606d9f046945fff19ea92d7b1a10f16b", "testCaseId": "e89a5a0e9aefe451ee262eba82370b01", "fullName": "tests.login_test.TestLogin#test_logout", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('test_setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "login_test"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-BFIIM5B"}, {"name": "thread", "value": "14468-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.login_test"}]}